name: parkirboss
description: "Parkir Boss - Smart Parking Management System"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.2
  shared_preferences: ^2.2.3
  image_picker: ^1.0.7
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
